//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ACCID { get; set; }
        public string Acc_Num { get; set; }
        public Nullable<int> Acc_Parent_Num { get; set; }
        public string Acc_Aname { get; set; }
        public Nullable<int> UserNumbers { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ConstNumbers { get; set; }
        public Nullable<int> Acc_Level { get; set; }
        public Nullable<int> Acc_Type { get; set; }
        public Nullable<decimal> Acc_Depet { get; set; }
        public Nullable<decimal> Acc_Credit { get; set; }
        public Nullable<decimal> Acc_Balance { get; set; }
        public Nullable<int> StatementNumberWared { get; set; }
        public Nullable<int> StatementNumberSader { get; set; }
        public Nullable<int> EmpNumbers { get; set; }
        public Nullable<int> ConnNumbers { get; set; }
        public Nullable<System.DateTime> TheDate { get; set; }
        public byte[] EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string AccNote { get; set; }
        public Nullable<byte> NumOFEditAcc { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public byte[] AddUser { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        public virtual Tb_DailyrestictionsHead Tb_DailyrestictionsHead { get; set; }
        public virtual Tb_Employee Tb_Employee { get; set; }
        public virtual Tb_IncomingTotals Tb_IncomingTotals { get; set; }
        public virtual Tb_Outgoing Tb_Outgoing { get; set; }
        public virtual Tb_Users Tb_Users { get; set; }
    }
}
