//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencise1
    {
        public int CurrencyNumber { get; set; }
        public Nullable<int> UserNumber { get; set; }
        public string UserName { get; set; }
        public string CurrencyName { get; set; }
        public string ArabicSymbol { get; set; }
        public string EnglishSymbol { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Note { get; set; }
    }
}
