//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currencies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Currencies()
        {
            this.Account = new HashSet<Account>();
        }
    
        public int CommntNumber { get; set; }
        public Nullable<int> UserNumbers { get; set; }
        public string Currency { get; set; }
        public string Source { get; set; }
        public Nullable<int> Amount { get; set; }
        public string CommntCurrency { get; set; }
        public string DestinationCurrency { get; set; }
        public string DocumentType { get; set; }
        public string ConstNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account { get; set; }
        public virtual Tb_Users Tb_Users { get; set; }
    }
}
