//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTAEMEntities : DbContext
    {
        public DBTAEMEntities()
            : base("name=DBTAEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
        public virtual DbSet<Currencise1> Currencise1 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tb_AccountStop> Tb_AccountStop { get; set; }
        public virtual DbSet<Tb_Blacklist> Tb_Blacklist { get; set; }
        public virtual DbSet<Tb_Box> Tb_Box { get; set; }
        public virtual DbSet<Tb_BuyingSelling> Tb_BuyingSelling { get; set; }
        public virtual DbSet<Tb_ConcelTransfer> Tb_ConcelTransfer { get; set; }
        public virtual DbSet<Tb_ConfirmedTransfer> Tb_ConfirmedTransfer { get; set; }
        public virtual DbSet<Tb_CurrenciesPrices> Tb_CurrenciesPrices { get; set; }
        public virtual DbSet<Tb_Currencise> Tb_Currencise { get; set; }
        public virtual DbSet<Tb_CustomerExchangeReceiptBonds> Tb_CustomerExchangeReceiptBonds { get; set; }
        public virtual DbSet<Tb_DailyRestictionsDitales> Tb_DailyRestictionsDitales { get; set; }
        public virtual DbSet<Tb_DailyrestictionsHead> Tb_DailyrestictionsHead { get; set; }
        public virtual DbSet<Tb_DeportationTransfar> Tb_DeportationTransfar { get; set; }
        public virtual DbSet<Tb_DoubleRestictions> Tb_DoubleRestictions { get; set; }
        public virtual DbSet<Tb_Employee> Tb_Employee { get; set; }
        public virtual DbSet<Tb_Entities> Tb_Entities { get; set; }
        public virtual DbSet<Tb_Groups> Tb_Groups { get; set; }
        public virtual DbSet<Tb_IncomingTotals> Tb_IncomingTotals { get; set; }
        public virtual DbSet<Tb_InventoryBox> Tb_InventoryBox { get; set; }
        public virtual DbSet<Tb_MatchingAccounts> Tb_MatchingAccounts { get; set; }
        public virtual DbSet<Tb_Outgoing> Tb_Outgoing { get; set; }
        public virtual DbSet<Tb_PersonalInformation> Tb_PersonalInformation { get; set; }
        public virtual DbSet<Tb_RoofingAccounts> Tb_RoofingAccounts { get; set; }
        public virtual DbSet<Tb_RwcipientCard> Tb_RwcipientCard { get; set; }
        public virtual DbSet<Tb_SimpleRegistBond> Tb_SimpleRegistBond { get; set; }
        public virtual DbSet<Tb_Transfar> Tb_Transfar { get; set; }
        public virtual DbSet<Tb_Users> Tb_Users { get; set; }
    }
}
