//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_BuyingSelling
    {
        public int BondNumber { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<int> UserNumbers { get; set; }
        public string AmountCcount { get; set; }
        public string AmountPay { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> AmountValue { get; set; }
        public string ValueCcount { get; set; }
        public string ValueCurrency { get; set; }
        public string BondName { get; set; }
        public Nullable<System.DateTime> TheDate { get; set; }
        public string castamerName { get; set; }
        public string ValuePay { get; set; }
        public string Note { get; set; }
    
        public virtual Tb_Users Tb_Users { get; set; }
    }
}
