//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ConcelTransfer
    {
        public int Numbers { get; set; }
        public Nullable<int> UserNumbers { get; set; }
        public string Agent { get; set; }
        public Nullable<int> TransfarNumber { get; set; }
        public Nullable<int> TransfarAmount { get; set; }
        public Nullable<int> GlobleNumber { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string Note { get; set; }
    
        public virtual Tb_Users Tb_Users { get; set; }
    }
}
