//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_CustomerExchangeReceiptBonds
    {
        public int BondNumber { get; set; }
        public Nullable<int> UserNumbers { get; set; }
        public string ExchangeMethod { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Currency { get; set; }
        public string MethodExchangeReceipt { get; set; }
        public string AmountName { get; set; }
        public string UserName { get; set; }
        public string Handling { get; set; }
        public Nullable<int> AmountNumberMadin { get; set; }
        public Nullable<int> AmountNumberDain { get; set; }
        public string Box { get; set; }
        public string BondStatus { get; set; }
        public Nullable<int> AccountAmount { get; set; }
        public string AccountCurrency { get; set; }
        public Nullable<System.DateTime> TheDate { get; set; }
        public string Note { get; set; }
    
        public virtual Tb_Users Tb_Users { get; set; }
    }
}
