//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_CurrenciesPrices
    {
        public int CurrencyPriceNumber { get; set; }
        public Nullable<int> CurrencyNumber { get; set; }
        public string TtranferFrom { get; set; }
        public string TtranferTo { get; set; }
        public Nullable<int> TtranferPrice { get; set; }
        public Nullable<int> PurchPrice { get; set; }
        public Nullable<int> SellingPrice { get; set; }
        public Nullable<int> LowPrice { get; set; }
        public Nullable<int> HeghtPrice { get; set; }
        public Nullable<int> LowPricePay { get; set; }
        public Nullable<int> LowPriceSelling { get; set; }
        public Nullable<int> HeghtPricePay { get; set; }
        public Nullable<int> HeghtPriceSelling { get; set; }
        public string Note { get; set; }
    
        public virtual Currencise Currencise { get; set; }
    }
}
