//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_CurrenciesPrices
    {
        public int CurrencyPriceNumber { get; set; }
        public Nullable<int> CurrencyNumber { get; set; }
        public string TtranferFrom { get; set; }
        public string TtranferTo { get; set; }
        public Nullable<decimal> TtranferPrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<decimal> LowPrice { get; set; }
        public Nullable<decimal> HighestPrice { get; set; }
        public Nullable<decimal> LowPricePurchasing { get; set; }
        public Nullable<decimal> LowPriceSelling { get; set; }
        public Nullable<decimal> HighestPricePurchasing { get; set; }
        public Nullable<decimal> HighestPriceSelling { get; set; }
        public string Note { get; set; }
    
        public virtual Tb_Currencise Tb_Currencise { get; set; }
    }
}
