//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_DailyrestictionsHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_DailyrestictionsHead()
        {
            this.Accounts = new HashSet<Account>();
            this.Tb_DailyRestictionsDitales = new HashSet<Tb_DailyRestictionsDitales>();
        }
    
        public int ConstNumber { get; set; }
        public Nullable<System.DateTime> ConstDate { get; set; }
        public string Currency { get; set; }
        public string AccountNameMadin { get; set; }
        public string AccountNameDain { get; set; }
        public Nullable<int> AccountMadin { get; set; }
        public Nullable<int> AccountDain { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> GroupAmountMadin { get; set; }
        public Nullable<int> GroupAmountDain { get; set; }
        public string Statements { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_DailyRestictionsDitales> Tb_DailyRestictionsDitales { get; set; }
    }
}
