//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Employee()
        {
            this.Account = new HashSet<Account>();
        }
    
        public int EmpNumber { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> UserNumbers { get; set; }
        public Nullable<int> AccountNumberEmp { get; set; }
        public Nullable<int> AccountEmp { get; set; }
        public string Functions { get; set; }
        public Nullable<int> Salary { get; set; }
        public string SalariesAccountName { get; set; }
        public string EmpStatus { get; set; }
        public string RegistNote { get; set; }
        public Nullable<System.DateTime> RegistDate { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account { get; set; }
        public virtual Tb_Users Tb_Users { get; set; }
    }
}
