//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_InventoryBox
    {
        public int BoxNumber { get; set; }
        public string Box { get; set; }
        public Nullable<int> UserNumbers { get; set; }
        public string Currency { get; set; }
        public Nullable<int> SystemBalance { get; set; }
        public Nullable<int> InventoryBalance { get; set; }
        public Nullable<int> Differenc { get; set; }
        public string Note { get; set; }
    
        public virtual Tb_Users Tb_Users { get; set; }
    }
}
