//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_PersonalInformation
    {
        public int Numbers { get; set; }
        public Nullable<int> UserNumbers { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Nationality { get; set; }
        public string SigntureImg { get; set; }
        public string FrontImg { get; set; }
        public string BackImg { get; set; }
        public string PersonalImg { get; set; }
        public Nullable<System.DateTime> AnendDate { get; set; }
        public string SideRelease { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> IdNumber { get; set; }
        public string Fax { get; set; }
        public string Note { get; set; }
    
        public virtual Tb_Users Tb_Users { get; set; }
    }
}
