//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Transfar
    {
        public Nullable<int> TransfarNumber { get; set; }
        public int BondNumber { get; set; }
        public string SenderName { get; set; }
        public string RecipientName { get; set; }
        public string PhoneNumberSender { get; set; }
        public string PhoneNumberRecipient { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> ReceiptAmount { get; set; }
        public string Currency { get; set; }
        public string Source { get; set; }
        public string Side { get; set; }
        public string Comm { get; set; }
        public string ServicrCurrency { get; set; }
        public Nullable<int> Price { get; set; }
        public string ReceiptCurrency { get; set; }
        public string ArrestMethod { get; set; }
        public string ReceiptAccount { get; set; }
        public Nullable<int> StatementNumberWared { get; set; }
        public Nullable<int> StatementNumberSader { get; set; }
        public Nullable<int> IDNunber { get; set; }
        public Nullable<int> CurrencyNumber { get; set; }
        public Nullable<int> UserNumbers { get; set; }
        public Nullable<int> NumberTT { get; set; }
        public Nullable<int> ReceiptAmountWared { get; set; }
        public Nullable<int> TransfarAmount { get; set; }
        public string RegistStatus { get; set; }
        public string AccredStatus { get; set; }
        public string TransfarStatus { get; set; }
        public string ConfirmStatus { get; set; }
        public string Agent { get; set; }
        public string AgentComm { get; set; }
        public string ReceiptCurrencyWared { get; set; }
        public string Note { get; set; }
    
        public virtual Tb_Currencise Tb_Currencise { get; set; }
        public virtual Tb_DeportationTransfar Tb_DeportationTransfar { get; set; }
        public virtual Tb_IncomingTotals Tb_IncomingTotals { get; set; }
        public virtual Tb_Outgoing Tb_Outgoing { get; set; }
        public virtual Tb_RwcipientCard Tb_RwcipientCard { get; set; }
        public virtual Tb_Users Tb_Users { get; set; }
    }
}
