//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeAndMony.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Users()
        {
            this.Account = new HashSet<Account>();
            this.Currencies = new HashSet<Currencies>();
            this.Tb_AccountStop = new HashSet<Tb_AccountStop>();
            this.Tb_Blacklist = new HashSet<Tb_Blacklist>();
            this.Tb_Box = new HashSet<Tb_Box>();
            this.Tb_BuyingSelling = new HashSet<Tb_BuyingSelling>();
            this.Tb_ConcelTransfer = new HashSet<Tb_ConcelTransfer>();
            this.Tb_ConfirmedTransfer = new HashSet<Tb_ConfirmedTransfer>();
            this.Tb_Currencise = new HashSet<Tb_Currencise>();
            this.Tb_CustomerExchangeReceiptBonds = new HashSet<Tb_CustomerExchangeReceiptBonds>();
            this.Tb_DeportationTransfar = new HashSet<Tb_DeportationTransfar>();
            this.Tb_DoubleRestictions = new HashSet<Tb_DoubleRestictions>();
            this.Tb_Employee = new HashSet<Tb_Employee>();
            this.Tb_Entities = new HashSet<Tb_Entities>();
            this.Tb_Groups = new HashSet<Tb_Groups>();
            this.Tb_IncomingTotals = new HashSet<Tb_IncomingTotals>();
            this.Tb_InventoryBox = new HashSet<Tb_InventoryBox>();
            this.Tb_MatchingAccounts = new HashSet<Tb_MatchingAccounts>();
            this.Tb_Outgoing = new HashSet<Tb_Outgoing>();
            this.Tb_PersonalInformation = new HashSet<Tb_PersonalInformation>();
            this.Tb_RoofingAccounts = new HashSet<Tb_RoofingAccounts>();
            this.Tb_RwcipientCard = new HashSet<Tb_RwcipientCard>();
            this.Tb_SimpleRegistBond = new HashSet<Tb_SimpleRegistBond>();
            this.Tb_Transfar = new HashSet<Tb_Transfar>();
        }
    
        public int UserNumber { get; set; }
        public string UserName { get; set; }
        public string UserStatus { get; set; }
        public Nullable<System.DateTime> TheDate { get; set; }
        public string UserGroup { get; set; }
        public string ChangePassword { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currencies> Currencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_AccountStop> Tb_AccountStop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Blacklist> Tb_Blacklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Box> Tb_Box { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_BuyingSelling> Tb_BuyingSelling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ConcelTransfer> Tb_ConcelTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ConfirmedTransfer> Tb_ConfirmedTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Currencise> Tb_Currencise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_CustomerExchangeReceiptBonds> Tb_CustomerExchangeReceiptBonds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_DeportationTransfar> Tb_DeportationTransfar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_DoubleRestictions> Tb_DoubleRestictions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Employee> Tb_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Entities> Tb_Entities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Groups> Tb_Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_IncomingTotals> Tb_IncomingTotals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_InventoryBox> Tb_InventoryBox { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_MatchingAccounts> Tb_MatchingAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Outgoing> Tb_Outgoing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_PersonalInformation> Tb_PersonalInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_RoofingAccounts> Tb_RoofingAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_RwcipientCard> Tb_RwcipientCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_SimpleRegistBond> Tb_SimpleRegistBond { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Transfar> Tb_Transfar { get; set; }
    }
}
