using System;
using System.Windows.Forms;
using System.Data.Entity;

namespace ExchangeAndMony.pages.accountsInterface.accountsInitializatuionInterface
{
    public partial class BoxGuide : DevExpress.XtraEditors.XtraForm
    {

        // nameDocument.Text="سند قيد بسيط";
        public BoxGuide()
        {

            // nameDocument.Text = "سند قيد بسيط";
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ExchangeAndMony.model.DBTAEMEntities dbContext = new ExchangeAndMony.model.DBTAEMEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Tb_Box.LoadAsync().ContinueWith(loadTask =>
            {
                    // Bind data to control when loading complete
                 tb_BoxBindingSource.DataSource = dbContext.Tb_Box.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void comboBox6_SelectedIndexChanged(object sender, EventArgs e)
        {

        }
    }
}