using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ExchangeAndMony.pages.accountsInterface.accountsInitializatuionInterface;
using System.Data.Entity;


namespace ExchangeAndMony.pages.accountsInterface.accountsInitializatuionInterface
{
    public partial class EmployeeGuide : DevExpress.XtraEditors.XtraForm
    {

        // nameDocument.Text="سند قيد بسيط";
        public EmployeeGuide()
        {

            // nameDocument.Text = "سند قيد بسيط";
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ExchangeAndMony.model.DBTAEMEntities dbContext = new ExchangeAndMony.model.DBTAEMEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Tb_Employee.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl_Divert.DataSource = dbContext.Tb_Employee.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void comboBox6_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void label5_Click(object sender, EventArgs e)
        {

        }

        private void btn_add_Click(object sender, EventArgs e)
        {

        }

        private void EmployeeGuide_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dBTAEMDataSet2.Tb_Employee' table. You can move, or remove it, as needed.
            this.tb_EmployeeTableAdapter1.Fill(this.dBTAEMDataSet2.Tb_Employee);
            // TODO: This line of code loads data into the 'dBTAEMDataSet1.Tb_Employee' table. You can move, or remove it, as needed.
            //this.tb_EmployeeTableAdapter.Fill(this.dBTAEMDataSet1.Tb_Employee);

        }
    }
}